version: "3.1"
services:
  nginx:
    image: nginx
    container_name: nginx_${APP_NAME}
    ports:
      - "8081:80"
    environment:
      - PHP_VERSION=${PHP_VERSION}
    links:
      - php_${PHP_VERSION}
    depends_on:
      - php_${PHP_VERSION}
    volumes:
      - ./public/:/var/www/${APP_NAME}.loc/public
      - ./docker/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
      - ./docker/nginx/${APP_NAME}.loc.conf:/etc/nginx/conf.d/${APP_NAME}.loc.conf
      - ./docker/nginx/${APP_NAME}-socket.conf:/etc/nginx/conf.d/${APP_NAME}-socket.conf
    networks:
        - net
      # default:
      #   aliases:
      #     - ${APP_NAME}.docker
      #     - ${APP_NAME}-socket.docker
    extra_hosts:
      - "host.docker.internal:host-gateway"

  php_8.0:
    container_name: php_${APP_NAME}
    depends_on:
      - mysql
      - redis
    volumes:
      # - ../game-laravel-client/:/var/www/${APP_NAME}.loc
      - ./:/var/www/${APP_NAME}.loc
      - ./docker/php_8.0/php-fpm.conf:/usr/local/etc/php-fpm.d/docker.conf
    working_dir: /var/www/${APP_NAME}.loc/app/Server/
    # command: bash -c "sleep 2 && php /var/www/${APP_NAME}.loc/artisan migrate --seed"
    build:
      context: ./docker/php_8.0
      dockerfile: Dockerfile
    links:
      - mysql
      - redis
    networks:
      - net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    image: mysql:8
    container_name: mysql_${APP_NAME}
    platform: linux/x86_64  # For Apple M1 support
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=${APP_NAME}
    ports:
      - "3307:3306"
    networks:
      - net

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin_${APP_NAME}
  #   ports:
  #     - ${PMA_PORT}:80
  #   environment:
  #     UPLOAD_LIMIT: 200000000
  #     MYSQL_ROOT_PASSWORD: root
  #   depends_on:
  #     - mysql
  #   links:
  #     - mysql:db

  redis:
    image: redis
    container_name: redis_${APP_NAME}
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    networks:
      - net

networks:
  net:
    driver: bridge
